# These are supported funding model platforms

github: [mehrdadh]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
buy_me_a_coffee: mehrdadh
